Dateisystem
TheLoraxxz/DHBW_GO_Projekt pull request #9
Opened 2022-12-02 11:50 UTC by GunJesus

Es läuft i guess

2022-12-02 18:59 UTC, TheLoraxxz requested changes
eine verbesserung danach kannstes pushen

2022-12-02 18:59 UTC, TheLorenzor commented on dateisystem/termin.go
> +	bytes, _ := bcrypt.GenerateFromPassword([]byte(id), 14)
hier reicht doch ein hashing mit dem kostenpunkt von 1

2022-12-02 20:59 UTC, CocoJasmin approved these changes
Noice, merci

2022-12-02 22:44 UTC, GunJesus commented on dateisystem/termin.go
> +	bytes, _ := bcrypt.GenerateFromPassword([]byte(id), 14)
Gutes Auge, Test Zeit ist von ~20s auf 1.5s gesunken

2022-12-03 16:00 UTC, TheLoraxxz approved these changes

2022-12-03 16:01 UTC, merged